#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/poll.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>

#define SERVER_PORT  3333

#define TRUE             1
#define FALSE            0
#define MAX_POLL_FDS     1000

/*************************************************************/
/* global data                                               */
/*************************************************************/
struct sockaddr_in   addr;            /* server socket address */
int                  timeout;         /* poll timeout */
struct pollfd        fds[MAX_POLL_FDS];/* poll fds */
int                  nfds = 1;        /* The number of all poll-fd */
int                  listen_sd = -1;  /* listen socket fd */
int                  on = 1;          /* 1:non-blocking; 0:blocking */
int                  end_server = FALSE; /* server running */


/*
* Add the new socket fd to fds array
*/
void add_client(int fd)
{
  /*
  * Set the socket to be nonblocking.
  */
  int rc = ioctl(fd, FIONBIO, (char *)&on);
  if (rc < 0)
  {
    perror("ioctl() failed");
    close(listen_sd);
    exit(-1);
  }

  fds[nfds].fd = fd;
  fds[nfds].events = POLLIN;

  nfds++;
  if (nfds > MAX_POLL_FDS){
    nfds = MAX_POLL_FDS;
  }

}

/*
* Delete the socket fd based on the index(del_i)
*/
void del_client(int del_i)
{
  close(fds[del_i].fd);

  for(int j = del_i; j < nfds; j++)
  {
    fds[j].fd = fds[j+1].fd;
  }
  nfds--;
}

/*
* Clean up all of the sockets that are open                
*/
void clean_client(void)
{
  for (int i = 0; i < nfds; i++)
  {
    if(fds[i].fd >= 0)
    close(fds[i].fd);
  }
}


int
main (int argc, char *argv[])
{

  int    len, rc;
  char   buffer[255];
  int    current_size = 0, i;
  int    new_sd = -1;     /* socket fd generated by the new connection */

  /*
  * Create an AF_INET stream socket to receive incoming      
  */
  listen_sd = socket(AF_INET, SOCK_STREAM, 0);
  if (listen_sd < 0)
  {
    perror("socket() failed");
    exit(-1);
  }

  /*
  * Allow socket descriptor to be reuseable 
  */
  rc = setsockopt(listen_sd, SOL_SOCKET,  SO_REUSEADDR,(char *)&on, sizeof(on));
  if (rc < 0)
  {
    perror("setsockopt() failed");
    close(listen_sd);
    exit(-1);
  }

  /*
  * Set socket to be nonblocking.
  */
  rc = ioctl(listen_sd, FIONBIO, (char *)&on);
  if (rc < 0)
  {
    perror("ioctl() failed");
    close(listen_sd);
    exit(-1);
  }

  /*
  * Bind the socket
  */
  memset(&addr, 0, sizeof(addr));
  addr.sin_family      = AF_INET;
  addr.sin_addr.s_addr = htonl(INADDR_ANY);
  addr.sin_port        = htons(SERVER_PORT);

  rc = bind(listen_sd,(struct sockaddr *)&addr, sizeof(addr));
  if (rc < 0)
  {
    perror("bind() failed");
    close(listen_sd);
    exit(-1);
  }

  /*
  * Set the listen backlog                            
  */
  rc = listen(listen_sd, MAX_POLL_FDS - 1);
  if (rc < 0)
  {
    perror("listen() failed");
    close(listen_sd);
    exit(-1);
  }

  /*
  * Initialize the pollfd structure              
  */
  memset(fds, 0 , sizeof(fds));

  /*
  * Set up the initial listening socket                       
  */
  fds[0].fd = listen_sd;
  fds[0].events = POLLIN;

  /*
  * Set the poll timeout
  */
  timeout = (3 * 60 * 1000);

  /*
  * Loop waiting for incoming connects or for incoming data  
  * on any of the connected sockets.                         
  */
  while (end_server == FALSE)
  {
    /*
    * Call poll() and wait 3 minutes for it to complete.    
    */
    printf("Waiting on poll()...\n");
    rc = poll(fds, nfds, timeout);

    if (rc < 0)
    {
      perror("  poll() failed");
      break;
    }

    if (rc == 0)
    {
      printf("  poll() timed out.\n");
      //break;
    }

    /*
    * One or more descriptors are readable.         
    * Need to determine which ones they are.                         
    */
    current_size = nfds;
    for (i = 0; i < current_size; i++)
    {
      /*
      * Loop through to find the descriptors that returned
      * POLLIN and determine whether it's the listening      
      * or the active connection.                             
      * 
      *  If revents equal to 0,it means connection is inactive.
      *  So,find the next descriptors.
      */
      if(fds[i].revents == 0){
        continue;
      }
        
      /*
      * If revents is not POLLIN, it's an unexpected result, 
      * log and end the server.                              
      */
      if(fds[i].revents != POLLIN)
      {
        printf("  Error! revents = %d\n", fds[i].revents);
        end_server = TRUE;
        del_client(i);
        break;
      }

      /*
      * it's the listening socket
      */
      if (fds[i].fd == listen_sd)
      {
        do
        {
          new_sd = accept(listen_sd, NULL, NULL);
          if (new_sd < 0)
          {
            if (errno != EWOULDBLOCK)
            {
              perror("  accept() failed");
              end_server = TRUE;
            }
            break;
          }

          /*
          * Add the new incoming connection to the pollfd structure         
          */ 
          add_client(new_sd);

        } while (new_sd != -1);
      }
      /*
      * This is not the listening socket, therefore an        
      * existing connection must be readable                  
      */
      else
      {
        /*
        * Receive all incoming data on this socket           
        * before we loop back and call poll again.           
        */
        do
        {
          /*
          * Receive data on this connection until the      
          * recv fails with EWOULDBLOCK. If any other       
          * failure occurs, we will close the                
          * connection.                                      
          */
          rc = recv(fds[i].fd, buffer, sizeof(buffer), 0);

          if (rc < 0)
          {
            if (errno != EWOULDBLOCK)
            {
              perror("  recv() failed");
              del_client(i);
            }

            printf("  errno == EWOULDBLOCK.\n");
            break;
          }

          /*
          * Check to see if the connection has been closed by the client                             
          */
          if (rc == 0)
          {
            printf("The connection has been closed by the client.\n");
            del_client(i);
            break;
          }

          /*
          * Data was received                                
          */
          len = rc;
          printf("  %d bytes received\n", len);

          /*
          * Echo the data back to the client                 
          */
          rc = send(fds[i].fd, buffer, len, 0);
          if (rc < 0)
          {
            perror("  send() failed");
            del_client(i);
            break;
          }

        } while(TRUE);

      }
    } /* End of loop through pollable descriptors */

  }

  /*
  * Clean up all of the sockets that are open                
  */
  clean_client();

  return 0;
}
